title: ₠Quantum

debug:
  dist: false
  compress: true
  shortcodes: true

readme_index:
  with_frontmatter: true

remote_theme: eQ19/parser

google:
  gtag: GTM-PGWT4RS
  adsense: ca-pub-3677197599836940
