title: eQuantum

debug:
  dist: false
  compress: true
  shortcodes: true

google:
  gtag: GTM-PGWT4RS
  adsense: ca-pub-3677197599836940

#remote_theme: FeedTheme/jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme@2.0.10
